[package]
name = "benchmark"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
silent = { path = "../silent" }

[dev-dependencies]
criterion = "0.7"

[[bench]]
name = "route_benchmark"
path = "benches/route_benchmark.rs"
harness = false
