[package]
edition = "2021"
name = "middleware_layered"
version = "0.1.0"
license = "Apache-2.0"

[dependencies]
async-trait = "0.1"
silent = {path = "../../silent"}
tokio = {version = "1.0", features = ["full"]}
