[workspace]
members = ["silent", "examples/*", "benchmark"]
default-members = ["silent"]
resolver = "2"

[workspace.package]
edition = "2024"
authors = ["Hubert Shelley <hubertshelley@163.com>"]
homepage = "https://github.com/hubertshelley/silent"
license = "Apache-2.0"
readme = "./readme.md"
repository = "https://github.com/hubertshelley/silent"
version = "2.2.0"

[workspace.dependencies]
async-trait = "0.1.86"
tokio = { version = "1.43.0", features = ["full"] }
tonic = "0.12.3"
prost = "0.13"
http = "1.2.0"
hyper-util = "0.1.10"
hyper = "1.5.2"
tower = "0.5.2"
tonic-build = "0.12.3"
tokio_wasi = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1.17", features = ["net"] }
futures-util = "0.3.31"
once_cell = "1.20.2"
tokio-tungstenite = "0.26.1"
tracing-subscriber = "0.3"
headers = "0.4.0"
serde = { version = "1.0.217", features = ["derive"] }
uuid = { version = "1.11.0", features = ["serde", "v4"] }
parking_lot = "0.12"
chrono = "0.4"
dlopen2 = { version = "0.7.0", features = ["derive"] }
h2 = "0.4.7"
