[workspace]
members = ["silent*", "examples/*"]
default-members = ["silent", ]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Hubert Shelley <hubertshelley@163.com>"]
homepage = "https://github.com/hubertshelley/silent"
license = "Apache-2.0"
readme = "./readme.md"
repository = "https://github.com/hubertshelley/silent"
version = "0.11.6"
