[package]
name = "example-websocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
silent = { path = "../../silent", features = ["ws"] }
tokio = { version = "1.29.1", features = ["full"] }
tokio-tungstenite = "0.19.0"
futures-util = "0.3.28"
backtrace = "0.3.68"
headers = "0.3.8"
