[package]
name = "example-websocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
silent = { path = "../../silent", features = ["ws"] }
tokio = { version = "1.34.0", features = ["full"] }
tokio-tungstenite = "0.20.1"
futures-util = "0.3.29"
backtrace = "0.3.69"
headers = "0.4.0"
