[package]
name = "examples_plugin_test"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
silent = { path = "../../silent" }
crossbeam-epoch = "0.9.18"
dlopen2 = { version = "0.7.0", features = ["derive"] }
