[package]
name = "silent"
edition.workspace = true
authors.workspace = true
categories = ["web-programming::web", "web-programming::web-framework"]
documentation = "https://docs.rs/silent/"
description = """
Silent Web Framework
"""
homepage.workspace = true
keywords = ["web", "web-framework"]
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["server", "test", "static"]
full = ["server", "wasi", "static", "test"]
server = ["tokio/fs", "tokio/net", "tokio/rt-multi-thread", "tokio/signal"]
static = []
wasi = ["tokio/sync"]
test = ["tokio/macros", "tokio/rt"]

[dependencies]
thiserror = "1"
hyper = { version = "1.0.0-rc.3", features = ["full"] }
tokio = { version = "1", optional = true }
bytes = "1"
http-body-util = "0.1.0-rc.2"
tracing = "0.1"
tracing-subscriber = "0.3"
async-trait = "0.1"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1"
uuid = "1"
url = "2"
serde_urlencoded = "0.7"
multimap = { version = "0.9", features = ["serde"] }
mime = "0.3"
tempfile = "3"
textnonce = "1"
multer = "2"
futures-util = { version = "0.3", features = ["io"] }
