[package]
name = "silent"
edition.workspace = true
authors.workspace = true
categories = ["web-programming::http-server", "web-programming::websocket", "network-programming", "asynchronous"]
documentation = "https://docs.rs/silent/"
description = """
Silent Web Framework
"""
homepage.workspace = true
keywords = ["web", "web-framework"]
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["server", "test", "static"]
full = ["admin", "server", "ws", "sse", "security", "static", "session", "cookie", "template", "test"]
admin = ["server", "sse", "template", "session"]
server = ["tokio/fs", "tokio/net", "tokio/rt-multi-thread", "tokio/signal"]
ws = []
sse = []
security = []
static = []
session = ["cookie"]
cookie = []
template = []
#wasi = ["tokio/sync"]
test = ["tokio/macros", "tokio/rt"]

[dependencies]
thiserror = "1.0.50"
hyper = { version = "1.0.1", features = ["full"] }
tokio = { version = "1.34.0", optional = true }
bytes = "1.5.0"
http-body-util = "0.1.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
async-trait = "0.1.74"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
uuid = "1.6.1"
url = "2.5.0"
serde_urlencoded = "0.7.1"
multimap = { version = "0.9.1", features = ["serde"] }
mime = "0.3.17"
tempfile = "3.8.1"
textnonce = "1.0.0"
#multer = "2.1.0"
silent-multer = "0.1.0"
futures-util = "0.3.29"
chrono = { version = "0.4.31", default-features = false, features = ["clock"] }
#tokio-tungstenite = "0.20.1"
silent-tokio-tungstenite = "0.1.0"
headers = "0.4.0"
tokio-stream = { version = "0.1.14", features = ["net"] }
pin-project = "1.1"
argon2 = "0.5.2"
pbkdf2 = { version = "0.12", features = ["simple"] }
aes-gcm = "0.10.3"
aes = "0.8"
rsa = "0.9.4"
cookie = { version = "0.18.0", features = ["secure", "percent-encode"] }
pin-project-lite = "0.2.13"
async-session = "3.0.0"
tera = "1.19.1"
http = "1.0.0"
http-body = "1.0.0"
