[package]
name = "silent"
edition.workspace = true
authors.workspace = true
categories = ["web-programming::http-server", "web-programming::websocket", "network-programming", "asynchronous"]
documentation = "https://docs.rs/silent/"
description = """
Silent Web Framework
"""
homepage.workspace = true
keywords = ["web", "web-framework"]
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["server", "test", "static"]
full = ["admin", "server", "ws", "sse", "security", "static", "session", "cookie", "template", "wasi", "test"]
admin = ["server", "sse", "template", "session"]
server = ["tokio/fs", "tokio/net", "tokio/rt-multi-thread", "tokio/signal"]
ws = []
sse = []
security = []
static = []
session = ["cookie"]
cookie = []
template = []
wasi = ["tokio/sync"]
test = ["tokio/macros", "tokio/rt"]

[dependencies]
thiserror = "1.0.47"
hyper = { version = "1.0.0-rc.4", features = ["full"] }
tokio = { version = "1.32.0", optional = true }
bytes = "1.4.0"
http-body-util = "0.1.0-rc.3"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
async-trait = "0.1.73"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
uuid = "1.4.1"
url = "2.4.0"
serde_urlencoded = "0.7.1"
multimap = { version = "0.9.0", features = ["serde"] }
mime = "0.3.17"
tempfile = "3.7.1"
textnonce = "1.0.0"
multer = "2.1.0"
futures-util = "0.3.28"
chrono = { version = "0.4.26", default-features = false, features = ["clock"] }
tokio-tungstenite = "0.20.0"
headers = "0.3.8"
tokio-stream = { version = "0.1.14", features = ["net"] }
pin-project = "1.1"
argon2 = "0.5.1"
pbkdf2 = { version = "0.12", features = ["simple"] }
aes-gcm = "0.10.2"
aes = "0.8"
rsa = "0.9.2"
cookie = { version = "0.17.0", features = ["secure", "percent-encode"] }
pin-project-lite = "0.2.12"
async-session = "3.0.0"
tera = "1.19.0"
