[package]
name = "silent"
edition = "2021"
authors = ["Hubert Shelley <hubertshelley@163.com>"]
categories = ["web-programming::web", "web-programming::web-framework"]
documentation = "https://docs.rs/"
description = """
Silent Web Framework
"""
homepage = "https://github.com/hubertshelley/silent"
keywords = ["web", "web-framework"]
license = "Apache-2.0"
readme = "./readme.md"
repository = "https://github.com/hubertshelley/silent"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
hyper = { version = "1.0.0-rc.3", features = ["full"] }
tokio = { version = "1", features = ["full"] }
bytes = "1"
http-body-util = "0.1.0-rc.2"
tracing = "0.1"
tracing-subscriber = "0.3"
async-trait = "0.1"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1"
uuid = "1"
url = "2"
serde_urlencoded = "0.7"
multimap = { version = "0.9", features = ["serde"] }
mime = "0.3"
tempfile = "3"
textnonce = "1"
multer = "2"
futures-util = { version = "0.3", features = ["io"] }
