[package]
name = "silent"
edition.workspace = true
authors.workspace = true
categories = ["web-programming::http-server", "web-programming::websocket", "network-programming", "asynchronous"]
documentation = "https://docs.rs/silent/"
description = """
Silent Web Framework
"""
homepage.workspace = true
keywords = ["web", "web-framework"]
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["server", "test", "static"]
full = ["admin", "server", "multipart", "ws", "sse", "security", "static", "session", "cookie", "template", "test", "scheduler"]
admin = ["server", "sse", "template", "session"]
server = ["tokio/fs", "tokio/net", "tokio/rt-multi-thread", "tokio/signal"]
ws = []
multipart = []
sse = []
security = []
static = []
session = ["cookie"]
cookie = []
template = []
#wasi = ["tokio/sync"]
test = ["tokio/macros", "tokio/rt"]
scheduler = []

[dependencies]
thiserror = "1.0.57"
hyper = { version = "1.2.0", features = ["full"] }
tokio = { version = "1.36.0", optional = true }
bytes = "1.5.0"
http-body-util = "0.1.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
async-trait = "0.1.77"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
uuid = "1.7.0"
url = "2.5.0"
serde_urlencoded = "0.7.1"
multimap = { version = "0.10.0", features = ["serde"] }
mime = "0.3.17"
tempfile = "3.10.1"
textnonce = "1.0.0"
multer = "3.0.0"
#silent-multer = "0.1.0"
futures-util = "0.3.30"
chrono = { version = "0.4.34", default-features = false, features = ["clock"] }
tokio-tungstenite = "0.21.0"
#silent-tokio-tungstenite = "0.1.0"
headers = "0.4.0"
tokio-stream = { version = "0.1.14", features = ["net"] }
pin-project = "1.1"
argon2 = "0.5.3"
pbkdf2 = { version = "0.12", features = ["simple"] }
aes-gcm = "0.10.3"
aes = "0.8"
# remove rsa because it's not save
#rsa = "0.9.6"
cookie = { version = "0.18.0", features = ["secure", "percent-encode"] }
pin-project-lite = "0.2.13"
async-session = "3.0.0"
tera = "1.19.1"
http = "1.0.0"
http-body = "1.0.0"
futures = "0.3.30"
tokio-util = "0.7.10"
anyhow = "1.0.80"
cron = "0.12.0"
