[package]
name = "silent"
edition.workspace = true
authors.workspace = true
categories = ["web-programming::http-server", "web-programming::websocket", "network-programming", "asynchronous"]
documentation = "https://docs.rs/silent/"
description = """
Silent Web Framework
"""
homepage.workspace = true
keywords = ["web", "web-framework"]
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["server", "test", ]
full = ["admin", "server", "multipart", "upgrade", "sse", "security", "static", "session", "cookie", "template", "test", "scheduler", "grpc"]
admin = ["server", "sse", "template", "session"]
server = ["tokio/net", "tokio/rt-multi-thread", "tokio/signal"]
upgrade = ["dep:tokio-tungstenite"]
multipart = ["tokio/fs", "dep:multer", "dep:multimap", "dep:tempfile", "dep:textnonce"]
sse = ["dep:pin-project", "dep:tokio-stream"]
security = ["dep:argon2", "dep:pbkdf2", "dep:aes-gcm", "dep:aes"]
static = ["tokio/fs"]
session = ["cookie", "dep:async-session"]
cookie = ["dep:cookie"]
template = ["dep:tera"]
#wasi = ["tokio/sync"]
test = ["tokio/macros", "tokio/rt"]
scheduler = ["dep:cron"]
grpc = ["upgrade", "dep:axum", "dep:tower-service", "dep:pin-project-lite", "dep:pin-project", "dep:tokio-stream"]

[dependencies]
# Basic dependencies
thiserror = "1.0.60"
hyper = { version = "1.3.1", features = ["full"] }
hyper-util = { version = "0.1.3", features = ["server-auto", "tokio"] }
tokio = { version = "1.37.0", optional = true }
bytes = "1.6.0"
http-body-util = "0.1.1"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["local-time"] }
async-trait = "0.1.80"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
uuid = "1.8.0"
url = "2.5.0"
serde_urlencoded = "0.7.1"
mime = "0.3.17"
futures-util = "0.3.30"
chrono = { version = "0.4.38", default-features = false, features = ["clock"] }
tokio-tungstenite = { version = "0.21.0", optional = true }
headers = "0.4.0"
tokio-stream = { version = "0.1.15", features = ["net"], optional = true }
pin-project = { version = "1.1", optional = true }
pin-project-lite = { version = "0.2.14", optional = true }
http = "1.1.0"
http-body = "1.0.0"
futures = "0.3.30"
tokio-util = "0.7.11"
anyhow = "1.0.83"

# Scheduler
cron = { version = "0.12.1", optional = true }

# Multipart
multer = { version = "3.1.0", optional = true }
multimap = { version = "0.10.0", features = ["serde"], optional = true }
tempfile = { version = "3.10.1", optional = true }
textnonce = { version = "1.0.0", optional = true }


# Template
tera = { version = "1.19.1", optional = true }

# Session
async-session = { version = "3.0.0", optional = true }
cookie = { version = "0.18.1", features = ["secure", "percent-encode"], optional = true }

# Grpc
axum = { version = "0.7.5", optional = true }
tower-service = { version = "0.3.2", optional = true }

# Security
argon2 = { version = "0.5.3", optional = true }
pbkdf2 = { version = "0.12", features = ["simple"], optional = true }
aes-gcm = { version = "0.10.3", optional = true }
aes = { version = "0.8", optional = true }
# remove rsa because it's not save
#rsa = "0.9.6"
