[package]
name = "example-websocket-chat"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
silent = { path = "../../silent", features = ["upgrade"] }
tokio = { version = "1.39.2", features = ["full"] }
tokio-stream = { version = "0.1.15", features = ["net"] }
futures-util = { version = "0.3.30", default-features = false }
once_cell = "1.19.0"
