[package]
name = "example-websocket-chat"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
silent = { path = "../../silent", features = ["upgrade"] }
tokio = { workspace = true, features = ["full"] }
tokio-stream.workspace = true
futures-util.workspace = true
once_cell.workspace = true
