[package]
name = "example-websocket-chat"
version = "0.1.0"
edition.workspace = true
publish = false


[dependencies]
silent = { path = "../../silent", features = ["upgrade"] }
tokio = { workspace = true, features = ["full"] }
once_cell.workspace = true
