[package]
name = "example-websocket-chat"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
silent = { path = "../../silent", features = ["ws"] }
tokio = { version = "1.34.0", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["net"] }
futures-util = { version = "0.3.29", default-features = false }
once_cell = "1.18.0"
